// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkzWa0WD47Dr9tFYsT34pXpbRRtMo4g5g',
    appId: '1:353644599825:web:687ffd9db41d97a53defb0',
    messagingSenderId: '353644599825',
    projectId: 'task-manager-dba96',
    authDomain: 'task-manager-dba96.firebaseapp.com',
    storageBucket: 'task-manager-dba96.appspot.com',
    measurementId: 'G-JY7NVXWB02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIHNptC0eqsT1fpT5RnxMABUpo-FWiv1w',
    appId: '1:353644599825:android:9d73aaad18e870463defb0',
    messagingSenderId: '353644599825',
    projectId: 'task-manager-dba96',
    storageBucket: 'task-manager-dba96.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4h-eWc3vyXJ-bynl676xQXMSylspnFhg',
    appId: '1:353644599825:ios:c5e73136115cbb573defb0',
    messagingSenderId: '353644599825',
    projectId: 'task-manager-dba96',
    storageBucket: 'task-manager-dba96.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4h-eWc3vyXJ-bynl676xQXMSylspnFhg',
    appId: '1:353644599825:ios:c5e73136115cbb573defb0',
    messagingSenderId: '353644599825',
    projectId: 'task-manager-dba96',
    storageBucket: 'task-manager-dba96.appspot.com',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkzWa0WD47Dr9tFYsT34pXpbRRtMo4g5g',
    appId: '1:353644599825:web:68da85d96b05d6803defb0',
    messagingSenderId: '353644599825',
    projectId: 'task-manager-dba96',
    authDomain: 'task-manager-dba96.firebaseapp.com',
    storageBucket: 'task-manager-dba96.appspot.com',
    measurementId: 'G-S0QFB9VRLR',
  );

}